@Vibe.Api_HostAddress = http://localhost:5081

GET {{Vibe.Api_HostAddress}}/books/all
Accept: application/json

GET {{Vibe.Api_HostAddress}}/books/{id}
Accept: application/json

GET {{Vibe.Api_HostAddress}}/books/author/{author}
Accept: application/json

POST {{Vibe.Api_HostAddress}}/books
Content-Type: application/json

{
    "title": "Vibe Coding with C#",
    "author": "Ziggy Rafiq",
    "year": 2025
}

PUT {{Vibe.Api_HostAddress}}/books/{id}
Content-Type: application/json

{
    "id": "PUT_THE_BOOK_ID_HERE",
    "title": "Vibe Coding with C# - Updated Edition",
    "author": "Ziggy Rafiq",
    "year": 2025
}

DELETE {{Vibe.Api_HostAddress}}/books/{id}
Accept: application/json

 
###
